# ==============================================================================
# 06_Sensitivity_Analyses.R
#
# Integrative Prediction of Alzheimer’s Disease and Related Dementias Using
# Multi-Omics Aging Clocks and Genetic Data
#
# Purpose:
# - Run robustness/sensitivity analyses using outputs from scripts 03 and 05.
# - Avoid rebuilding train/test splits inside this script.
# - Evaluate prediction horizons, early-event exclusion, subgroup AUC/AUPRC,
#   and APOE/sex/age-of-onset sensitivity where variables are available.
#
# Supplementary outputs:
# - Figure A.9: subgroup/sensitivity AUC forest plot
# - Figure A.10: early-event exclusion cumulative incidence analysis
# - Horizon-specific risk-stratification tables
#
# Required inputs:
# - results/06_competing_risk/finegray_model_train.rds
# - results/06_competing_risk/survival_test_processed.rds
# - results/04_stepwise_xgboost/test_set_predictions_stepwise.csv
#
# Notes:
# - The exploratory clustering analysis from earlier drafts is intentionally
#   not included in the revised reviewer-facing workflow.
# - This script uses the exact held-out test split generated by scripts 03/05.
#
# Author: Shayan Mostafaei
# Updated for revision: 2026-06-22
# ==============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(readr)
  library(riskRegression)
  library(cmprsk)
  library(pROC)
  library(PRROC)
  library(ggplot2)
  library(scales)
  library(patchwork)
  library(forcats)
})

# ------------------------------------------------------------------------------
# USER SETTINGS
# ------------------------------------------------------------------------------

set.seed(20250101)

INPUT_RDS <- "data/biomarkers_complete.rds"

FG_MODEL_RDS <- file.path("results", "06_competing_risk", "finegray_model_train.rds")
SURV_TEST_RDS <- file.path("results", "06_competing_risk", "survival_test_processed.rds")
XGB_PRED_CSV <- file.path("results", "04_stepwise_xgboost", "test_set_predictions_stepwise.csv")

OUT_DIR <- file.path("results", "06_sensitivity")
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

ID_COL <- "f.eid"
SEX_COL <- "sex"
AGE_ONSET_COL <- "age_at_dementia_onset"
APOE4_COL <- "APOEe4_status"

FINAL_XGB_PRED_COL <- "pred_Model5_Add_MetaboAge"

HIGH_RISK_Q <- 0.75
HORIZONS <- c("3y" = 3 * 365.25, "5y" = 5 * 365.25, "7y" = 7 * 365.25, "9y" = 9 * 365.25)
EARLY_EVENT_DAYS <- 100

# ------------------------------------------------------------------------------
# LOAD INPUTS
# ------------------------------------------------------------------------------

if (!file.exists(FG_MODEL_RDS)) {
  stop("Missing Fine-Gray model. Run script 05 first: ", FG_MODEL_RDS)
}

if (!file.exists(SURV_TEST_RDS)) {
  stop("Missing processed survival test data. Run script 05 first: ", SURV_TEST_RDS)
}

if (!file.exists(XGB_PRED_CSV)) {
  stop("Missing XGBoost test predictions. Run script 03 first: ", XGB_PRED_CSV)
}

if (!file.exists(INPUT_RDS)) {
  stop("Missing original input data: ", INPUT_RDS)
}

fg_fit <- readRDS(FG_MODEL_RDS)
test_surv <- readRDS(SURV_TEST_RDS)
xgb_preds <- read_csv(XGB_PRED_CSV, show_col_types = FALSE)
df0 <- readRDS(INPUT_RDS)

if (!"id" %in% names(test_surv)) {
  stop("Processed survival test data must contain column `id`.")
}

if (!"ID" %in% names(xgb_preds)) {
  stop("XGBoost prediction file must contain column `ID`.")
}

if (!FINAL_XGB_PRED_COL %in% names(xgb_preds)) {
  stop("Missing final XGBoost prediction column: ", FINAL_XGB_PRED_COL)
}

test_surv <- test_surv %>% mutate(id = as.character(id))
xgb_preds <- xgb_preds %>% mutate(ID = as.character(ID))

# ------------------------------------------------------------------------------
# HELPER FUNCTIONS
# ------------------------------------------------------------------------------

predict_risk_vec <- function(fit, newdata, times) {
  r <- riskRegression::predictRisk(fit, newdata = newdata, times = times)
  as.numeric(if (is.matrix(r)) r[, 1] else r)
}

compute_group_shr <- function(df, group_var) {
  mm <- model.matrix(reformulate(group_var), data = df)[, -1, drop = FALSE]

  fit <- cmprsk::crr(
    ftime = df$time,
    fstatus = df$event,
    cov1 = mm,
    failcode = 1,
    cencode = 0
  )

  beta <- as.numeric(fit$coef)
  se <- sqrt(diag(fit$var))

  tibble(
    sHR = exp(beta),
    CI_low = exp(beta - 1.96 * se),
    CI_high = exp(beta + 1.96 * se),
    p_value = 2 * pnorm(-abs(beta / se))
  )
}

compute_continuous_shr_per1pct <- function(df, risk_vec) {
  cov_mat <- matrix(risk_vec, ncol = 1)

  fit <- cmprsk::crr(
    ftime = df$time,
    fstatus = df$event,
    cov1 = cov_mat,
    failcode = 1,
    cencode = 0
  )

  beta <- as.numeric(fit$coef)
  se <- sqrt(diag(fit$var))

  tibble(
    sHR_per_1pct = exp(beta * 0.01),
    CI_low = exp((beta - 1.96 * se) * 0.01),
    CI_high = exp((beta + 1.96 * se) * 0.01),
    p_value = 2 * pnorm(-abs(beta / se))
  )
}

make_cif_df <- function(time, event, group) {
  ci <- cmprsk::cuminc(ftime = time, fstatus = event, group = group)
  cause1_names <- names(ci)[grepl(" 1$", names(ci))]

  bind_rows(lapply(cause1_names, function(nm) {
    e <- ci[[nm]]
    grp <- sub(" 1$", "", nm)

    tibble(
      time = e$time,
      est = as.numeric(e$est),
      var = as.numeric(e$var),
      group = grp
    )
  })) %>%
    mutate(
      se = sqrt(var),
      lower = pmax(0, est - 1.96 * se),
      upper = pmin(1, est + 1.96 * se),
      group = factor(group, levels = c("Lower 75%", "Top 25%"))
    )
}

auc_ci_delong <- function(y, p) {
  ok <- !is.na(y) & !is.na(p)
  y <- y[ok]
  p <- p[ok]

  if (length(unique(y)) < 2) {
    return(tibble(AUC = NA_real_, Lower_CI = NA_real_, Upper_CI = NA_real_, N = length(y), Cases = sum(y == 1)))
  }

  roc_obj <- pROC::roc(
    response = y,
    predictor = p,
    levels = c(0, 1),
    direction = "auto",
    quiet = TRUE
  )

  ci <- as.numeric(pROC::ci.auc(roc_obj, method = "delong"))

  tibble(
    AUC = as.numeric(pROC::auc(roc_obj)),
    Lower_CI = ci[1],
    Upper_CI = ci[3],
    N = length(y),
    Cases = sum(y == 1)
  )
}

auprc_value <- function(y, p) {
  ok <- !is.na(y) & !is.na(p)
  y <- y[ok]
  p <- p[ok]

  if (length(unique(y)) < 2) return(NA_real_)

  pr <- PRROC::pr.curve(
    scores.class0 = p[y == 1],
    scores.class1 = p[y == 0],
    curve = FALSE
  )

  as.numeric(pr$auc.integral)
}

# ------------------------------------------------------------------------------
# 1. HORIZON ROBUSTNESS
# ------------------------------------------------------------------------------

shr_rows <- list()
threshold_rows <- list()
plot_list <- list()

for (nm in names(HORIZONS)) {
  t_days <- as.numeric(HORIZONS[[nm]])

  risk_vec <- predict_risk_vec(fg_fit, newdata = test_surv, times = t_days)
  q75 <- as.numeric(quantile(risk_vec, probs = HIGH_RISK_Q, na.rm = TRUE))

  group_vec <- factor(
    ifelse(risk_vec > q75, "Top 25%", "Lower 75%"),
    levels = c("Lower 75%", "Top 25%")
  )

  df_tmp <- test_surv %>%
    mutate(
      risk_horizon = risk_vec,
      risk_group = group_vec
    )

  shr_group <- compute_group_shr(df_tmp, "risk_group")
  shr_cont <- compute_continuous_shr_per1pct(df_tmp, risk_vec)

  event_summary <- df_tmp %>%
    group_by(risk_group) %>%
    summarise(
      n = n(),
      n_ADRD = sum(event == 1),
      n_death = sum(event == 2),
      n_censored = sum(event == 0),
      ADRD_percent = 100 * n_ADRD / n(),
      .groups = "drop"
    )

  write_csv(
    event_summary,
    file.path(OUT_DIR, paste0("riskgroup_event_summary_", nm, ".csv"))
  )

  shr_rows[[nm]] <- tibble(
    Horizon = nm,
    Days = t_days,
    Group_sHR = shr_group$sHR,
    Group_CI_low = shr_group$CI_low,
    Group_CI_high = shr_group$CI_high,
    Group_p = shr_group$p_value,
    Continuous_sHR_per_1pct = shr_cont$sHR_per_1pct,
    Continuous_CI_low = shr_cont$CI_low,
    Continuous_CI_high = shr_cont$CI_high,
    Continuous_p = shr_cont$p_value
  )

  threshold_rows[[nm]] <- tibble(
    Horizon = nm,
    Days = t_days,
    q75_threshold = q75
  )

  cif_df <- make_cif_df(df_tmp$time, df_tmp$event, df_tmp$risk_group)

  ann <- paste0(
    "sHR = ", sprintf("%.2f", shr_group$sHR),
    " (", sprintf("%.2f", shr_group$CI_low),
    "-", sprintf("%.2f", shr_group$CI_high), ")"
  )

  plot_list[[nm]] <- ggplot(cif_df, aes(x = time / 365.25, y = est, group = group)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.18) +
    geom_step(linewidth = 0.9) +
    scale_y_continuous(labels = percent_format(accuracy = 1)) +
    labs(
      title = paste0("Cumulative incidence by predicted-risk group: ", nm),
      subtitle = ann,
      x = "Follow-up time, years",
      y = "Cumulative incidence"
    ) +
    theme_classic(base_size = 12) +
    theme(
      legend.position = "top",
      plot.title = element_text(face = "bold", hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )
}

shr_by_horizon <- bind_rows(shr_rows)
thresholds_by_horizon <- bind_rows(threshold_rows)

write_csv(shr_by_horizon, file.path(OUT_DIR, "shr_by_horizon_test.csv"))
write_csv(thresholds_by_horizon, file.path(OUT_DIR, "riskgroup_thresholds_by_horizon.csv"))

if (length(plot_list) > 0) {
  horizon_panel <- wrap_plots(plot_list, ncol = 1)

  ggsave(
    filename = file.path(OUT_DIR, "cif_horizon_plots.png"),
    plot = horizon_panel,
    width = 9,
    height = 14,
    dpi = 500
  )
}

# ------------------------------------------------------------------------------
# 2. EARLY-EVENT EXCLUSION ROBUSTNESS
# ------------------------------------------------------------------------------

risk5 <- predict_risk_vec(fg_fit, newdata = test_surv, times = 5 * 365.25)
q75_5 <- as.numeric(quantile(risk5, probs = HIGH_RISK_Q, na.rm = TRUE))

group5 <- factor(
  ifelse(risk5 > q75_5, "Top 25%", "Lower 75%"),
  levels = c("Lower 75%", "Top 25%")
)

test_early <- test_surv %>%
  mutate(risk_5y = risk5, risk_group_5y = group5)

test_early_excluded <- test_early %>%
  filter(!(event %in% c(1, 2) & time <= EARLY_EVENT_DAYS))

early_exclusion_summary <- tibble(
  n_before = nrow(test_early),
  n_after = nrow(test_early_excluded),
  excluded_total_events = nrow(test_early) - nrow(test_early_excluded),
  excluded_ADRD = sum(test_early$event == 1 & test_early$time <= EARLY_EVENT_DAYS),
  excluded_death = sum(test_early$event == 2 & test_early$time <= EARLY_EVENT_DAYS)
)

write_csv(
  early_exclusion_summary,
  file.path(OUT_DIR, "early_event_exclusion_summary.csv")
)

if (nrow(test_early_excluded) > 0 && length(unique(test_early_excluded$risk_group_5y)) == 2) {
  shr_early <- compute_group_shr(test_early_excluded, "risk_group_5y")
  write_csv(shr_early, file.path(OUT_DIR, "early_event_exclusion_shr.csv"))

  cif_early <- make_cif_df(
    time = test_early_excluded$time,
    event = test_early_excluded$event,
    group = test_early_excluded$risk_group_5y
  )

  write_csv(
    cif_early,
    file.path(OUT_DIR, "FigureA10_early_event_exclusion_cif_data.csv")
  )

  ann_early <- paste0(
    "Excluding events within <= ", EARLY_EVENT_DAYS, " days; sHR = ",
    sprintf("%.2f", shr_early$sHR),
    " (", sprintf("%.2f", shr_early$CI_low),
    "-", sprintf("%.2f", shr_early$CI_high), ")"
  )

  p_early <- ggplot(cif_early, aes(x = time / 365.25, y = est, group = group)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.18) +
    geom_step(linewidth = 1) +
    scale_y_continuous(labels = percent_format(accuracy = 1)) +
    labs(
      title = "Early-event exclusion sensitivity analysis",
      subtitle = ann_early,
      x = "Follow-up time, years",
      y = "Cumulative incidence"
    ) +
    theme_classic(base_size = 13) +
    theme(
      legend.position = "top",
      plot.title = element_text(face = "bold", hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )

  ggsave(
    filename = file.path(OUT_DIR, "FigureA10_early_event_exclusion_cif.png"),
    plot = p_early,
    width = 8.5,
    height = 6,
    dpi = 500
  )
}

# ------------------------------------------------------------------------------
# 3. SUBGROUP DISCRIMINATION USING FINAL XGBOOST MODEL
# ------------------------------------------------------------------------------

subgroup_df <- xgb_preds %>%
  transmute(
    ID = as.character(ID),
    y_test = as.integer(y_test),
    final_pred = as.numeric(.data[[FINAL_XGB_PRED_COL]])
  )

df_anno <- df0 %>%
  mutate(ID = if (ID_COL %in% names(.)) as.character(.data[[ID_COL]]) else as.character(seq_len(nrow(.)))) %>%
  transmute(
    ID,
    sex = if (SEX_COL %in% names(df0)) as.factor(.data[[SEX_COL]]) else NA,
    apoe4 = if (APOE4_COL %in% names(df0)) as.factor(.data[[APOE4_COL]]) else NA,
    age_onset = if (AGE_ONSET_COL %in% names(df0)) suppressWarnings(as.numeric(.data[[AGE_ONSET_COL]])) else NA_real_
  )

subgroup_df <- subgroup_df %>%
  left_join(df_anno, by = "ID")

auc_rows <- list()
auprc_rows <- list()

# Overall
v <- auc_ci_delong(subgroup_df$y_test, subgroup_df$final_pred)
auc_rows[["Overall"]] <- v %>%
  mutate(Analysis = "Overall", Group = "All participants", .before = 1)

auprc_rows[["Overall"]] <- tibble(
  Analysis = "Overall",
  Group = "All participants",
  AUPRC = auprc_value(subgroup_df$y_test, subgroup_df$final_pred)
)

# Sex subgroup
if (!all(is.na(subgroup_df$sex))) {
  for (s in levels(droplevels(subgroup_df$sex))) {
    dd <- subgroup_df %>% filter(sex == s)
    key <- paste0("Sex_", s)

    auc_rows[[key]] <- auc_ci_delong(dd$y_test, dd$final_pred) %>%
      mutate(Analysis = "Sex", Group = as.character(s), .before = 1)

    auprc_rows[[key]] <- tibble(
      Analysis = "Sex",
      Group = as.character(s),
      AUPRC = auprc_value(dd$y_test, dd$final_pred)
    )
  }
}

# APOE-e4 subgroup
if (!all(is.na(subgroup_df$apoe4))) {
  for (g in levels(droplevels(subgroup_df$apoe4))) {
    dd <- subgroup_df %>% filter(apoe4 == g)
    key <- paste0("APOE4_", g)

    auc_rows[[key]] <- auc_ci_delong(dd$y_test, dd$final_pred) %>%
      mutate(Analysis = "APOE-e4 status", Group = as.character(g), .before = 1)

    auprc_rows[[key]] <- tibble(
      Analysis = "APOE-e4 status",
      Group = as.character(g),
      AUPRC = auprc_value(dd$y_test, dd$final_pred)
    )
  }
}

# Age-at-onset subgroup among cases versus all non-cases
if (!all(is.na(subgroup_df$age_onset))) {
  dd_early <- subgroup_df %>%
    mutate(early_case = ifelse(!is.na(age_onset) & age_onset < 65, 1, 0)) %>%
    filter(y_test == 0 | early_case == 1)

  auc_rows[["EarlyOnset"]] <- auc_ci_delong(dd_early$y_test, dd_early$final_pred) %>%
    mutate(Analysis = "Age at onset", Group = "Early-onset ADRD (<65)", .before = 1)

  auprc_rows[["EarlyOnset"]] <- tibble(
    Analysis = "Age at onset",
    Group = "Early-onset ADRD (<65)",
    AUPRC = auprc_value(dd_early$y_test, dd_early$final_pred)
  )

  dd_late <- subgroup_df %>%
    mutate(late_case = ifelse(!is.na(age_onset) & age_onset >= 65, 1, 0)) %>%
    filter(y_test == 0 | late_case == 1)

  auc_rows[["LateOnset"]] <- auc_ci_delong(dd_late$y_test, dd_late$final_pred) %>%
    mutate(Analysis = "Age at onset", Group = "Late-onset ADRD (>=65)", .before = 1)

  auprc_rows[["LateOnset"]] <- tibble(
    Analysis = "Age at onset",
    Group = "Late-onset ADRD (>=65)",
    AUPRC = auprc_value(dd_late$y_test, dd_late$final_pred)
  )
}

auc_subgroups <- bind_rows(auc_rows)
auprc_subgroups <- bind_rows(auprc_rows)

subgroup_summary <- auc_subgroups %>%
  left_join(auprc_subgroups, by = c("Analysis", "Group"))

write_csv(
  subgroup_summary,
  file.path(OUT_DIR, "FigureA9_subgroup_auc_auprc_summary.csv")
)

# ------------------------------------------------------------------------------
# 4. FIGURE A.9: SUBGROUP AUC FOREST PLOT
# ------------------------------------------------------------------------------

if (nrow(auc_subgroups) > 0) {
  plot_df <- auc_subgroups %>%
    mutate(
      Group_plot = paste0(Analysis, ": ", Group),
      Group_plot = fct_reorder(Group_plot, AUC),
      label = sprintf("%.2f (%.2f-%.2f); cases=%s", AUC, Lower_CI, Upper_CI, Cases)
    )

  p_auc <- ggplot(plot_df, aes(x = AUC, y = Group_plot)) +
    geom_vline(xintercept = 0.50, linetype = "dashed", linewidth = 0.5) +
    geom_errorbarh(aes(xmin = Lower_CI, xmax = Upper_CI), height = 0.18, linewidth = 0.8) +
    geom_point(size = 2.8) +
    geom_text(aes(label = label), hjust = -0.05, size = 3.1) +
    scale_x_continuous(limits = c(0.45, 1.00), breaks = seq(0.50, 1.00, by = 0.10)) +
    labs(
      title = "Sensitivity analyses: final XGBoost model discrimination",
      subtitle = "Held-out test-set ROC-AUC with DeLong 95% confidence intervals",
      x = "ROC-AUC",
      y = NULL
    ) +
    theme_classic(base_size = 12) +
    theme(
      plot.title = element_text(face = "bold", hjust = 0.5),
      plot.subtitle = element_text(hjust = 0.5)
    )

  ggsave(
    filename = file.path(OUT_DIR, "FigureA9_sensitivity_auc_forestplot.png"),
    plot = p_auc,
    width = 10,
    height = 7,
    dpi = 500
  )
}

# ------------------------------------------------------------------------------
# SAVE BUNDLE
# ------------------------------------------------------------------------------

saveRDS(
  list(
    shr_by_horizon = shr_by_horizon,
    thresholds_by_horizon = thresholds_by_horizon,
    early_exclusion_summary = early_exclusion_summary,
    subgroup_summary = subgroup_summary
  ),
  file.path(OUT_DIR, "sensitivity_results_bundle.rds")
)

cat("\nDONE: Sensitivity analyses completed.\n")
cat("Outputs written to:", OUT_DIR, "\n\n")
